### ISSUE TITLE
Question about the License

### ISSUE THREAD

**Issue by dupski** [camptocamp/odoo-cloud-platform#145]
Hi Guys

I have a question about the licensing of these modules. They are currently licensed under the AGPL.

We are likely to have customers that want to use Odoo's web portal for the general public to access their products and services. It is also likely that they will pay us to build some custom code for their system that they may not want to have to make available to their competitors.

If we use these modules, do we have to make all our customer's custom modules open source, since technically the general public can access and use their system? Or do we just have to make sure our direct customer can access the source code of there system if they want it?

Appreciate any advice on this!

**Comment by yvaucher** [comment]
@dupski The answer is yes, inheriting those modules makes your module open source in AGPL or LGPL.

Open source is a plus value for the user.
Open source modules code only needs to be available to the users. You don't have to publish them in public.

We have the same rules than OCA on this, which is the dependency chain.
Check https://odoo-community.org/blog/the-oca-blog-1/post/oca-odoo-meeting-on-licenses-21

**Comment by dupski** [comment]
Cool thanks for the info @yvaucher
