### ISSUE TITLE
session_redis: Sessions leaking to data_dir and crashing odoo

### ISSUE THREAD

**Issue by gustavovalverde** [camptocamp/odoo-cloud-platform#175]
I've found an odd behavior and it's that from time to time sessions leak to the `data_dir` causing the sessions folder to increase in size.

When there are thousands of sessions in the Folder, Odoo fails to start as this module tries to delete all of them first; failing to do so (or timing out in the process) hangs the server.

On environments like Kubernetes this causes that the container restarts infinitely (because of the healthchecks) until crashing.

**Comment by guewen** [comment]
I would be interested to know when odoo generate local files, I think we never observed this

**Comment by gustavovalverde** [comment]
Actually, I'm not completely sure myself. As I have my Odoo deployment in multiple Odoo services:
- Clients (multi-threaded)
- Chat (gevented)
- Crons (forked / multi-processing)

Even though all of them are using the module, maybe one of the modes does not respect the module?

**Comment by blaggacao** [comment]
It does so here: https://github.com/odoo/odoo/blob/9ebc6f2bfd9868398bb55bb782338beab9afcb2e/odoo/http.py#L1112

**Comment by blaggacao** [comment]
What's needed: client sessions (see dodoo WIP).
