### ISSUE TITLE
helm charts?

### ISSUE THREAD

**Issue by ayushin** [camptocamp/odoo-cloud-platform#200]
This repository is really awesome! We've been trying to run Odoo on GKE and it's been a battle - will definitely try this now.

I've seen your docker repository is there also a helm chart and is there a plan to make a terraform module?

**Comment by guewen** [comment]
Hi, thanks!

Currently, we are running on Rancher 1.x, but we plan to move to k8s, so we may publish something later.
I don't have details about the plans, nor if we'll work on a terraform module. @p-tombez may have more details.

**Comment by ayushin** [comment]
I'm making a quick and dirty adoptation of bitnami/odoo so once it is stabilised I'd be happy to share it with you guys perhaps we can benefit from co-operation here.

Main thing for k8s is that you have quite scalable configmaps concept that you pobably want to prefer to the docker environment driven lengthy startup scripts, so that's one discussion i'd be interested to have.

**Comment by nbessi** [comment]
Hello, 

We do not intend to publish our helm chart
