### ISSUE TITLE
attachment_s3: One directory per database

### ISSUE THREAD

**Issue by max3903** [camptocamp/odoo-cloud-platform#215]
# Context

Using version 12.0 with Digital Ocean Spaces

# Steps to reproduce

* Setup the AWS environment variables
* Create a database "MASTER"

# Result

* Files are stored directly in /BUCKETNAME/

# Expected result

* Files are stored in /BUCKETNAME/MASTER/

**Comment by max3903** [comment]
@guewen Is there any limitation to implementing this? Do you mind if I give it a shot?

**Comment by guewen** [comment]
I don't see any limitation, beside the fact that it should support both at least for backward compatibility (variable to chose one mode or the other?).

@p-tombez may have other thoughts

**Comment by p-tombez** [comment]
I have no objections

**Comment by max3903** [comment]
@guewen What about migrating instead of supporting 2 modes? If there is no directory in the bucket corresponding to the database name, we create one and move the files.

**Comment by yvaucher** [comment]
Followup of this discussion here:

https://github.com/camptocamp/odoo-cloud-platform/pull/218/files#r611813798

Backward compatibility is important because buckets cannot be renamed.

**Comment by yvaucher** [comment]
Closing as fixed for version 11.0 to 14.0
