### ISSUE TITLE
Push modules of this repo to Pypi?

### ISSUE THREAD

**Issue by max3903** [camptocamp/odoo-cloud-platform#241]
Is there any interest to push the modules of this repository to Pypi or even move the repository under the OCA?

**Comment by yvaucher** [comment]
@max3903 Seeing the growing interest of this repo it would make sense, it has now more than a hundred of forks and we see more and more contributions.

I don't know if all modules are applicable to enter the OCA though. We have a couple of Camptocamp specific stuff in there like the song we use with [anthem](https://github.com/camptocamp/anthem) :  https://github.com/camptocamp/odoo-cloud-platform/blob/13.0/cloud_platform/songs.py The modules should most likely be split across different OCA repositories.

Pushing to PyPi is definitely something that would help deploy with pip install !
(which is by default provided by the OCA bot)

Anyone else that wants to see this moving under OCA's umbrella?

Something to talk about during OCA days?

**Comment by nbessi** [comment]
We will probably not push those addons to pypi
