### ISSUE TITLE
[14.0] sessions_redis: "Lost Connection", "Reconnected" messages

### ISSUE THREAD

**Issue by JevinD** [camptocamp/odoo-cloud-platform#268]
**Issue:** 
When the session gets killed, the user sees "Lost Connection", "Reconnected" messages that pop up in the top right of the screen. This just happens over and over as you navigate until you go to logout and log back in.

**Expected outcome:** 
The user should see a message saying "Your session has expired".

**Comment by JevinD** [comment]
CC: @patrickrwilson

**Comment by nbessi** [comment]
Can not reproduce
