### ISSUE TITLE
[14.0] sessions_redis: inactivity timer

### ISSUE THREAD

**Issue by JevinD** [camptocamp/odoo-cloud-platform#269]
**issue**
When setting ODOO_SESSION_REDIS_EXPIRATION to 3600. This seems to timeout the user after 1 hour active or not.

Is there a way to start this timer after 1 hour of inactivity?

**Comment by yvaucher** [comment]
Currently session sliding is not supported/implemented.

I assume this would have to be implemented in the `get()` function. As by activity we can most likely define it by each time the session key is requested.
A simple call to `self.redis.expire(key, expiration)` just after we checked the session is valid might do the trick.
Around https://github.com/camptocamp/odoo-cloud-platform/blob/13.0/session_redis/session.py#L85

However while using an existing session does not reset the expiration, a new session is provided.

**Comment by JevinD** [comment]
@yvaucher Thank you

**Comment by JevinD** [comment]
CC: @patrickrwilson
