### ISSUE TITLE
[DISCUSSION] How to check if cron job fails

### ISSUE THREAD

**Issue by janikvonrotz** [camptocamp/odoo-cloud-platform#317]
https://github.com/camptocamp/odoo-cloud-platform/blob/185458f06bafa2b9800fd372629393220d0b6839/monitoring_status/controllers/main.py#L34

I've seen that you have module to check the status of the Odoo db. Is there a way to check for the status of the cron thread?

While running several Odoo docker instances I got a runtime error on the cron loop.

https://github.com/odoo/odoo/issues/79823

Not sure why I am the only one out there having this issue.

Now I am looking for a way to check the status of the cron thread across all instances. Maybe you got some input.

**Comment by guewen** [comment]
Maybe not the answer you expect, but you can find timeout errors in the odoo logs, from there, alerting is possible using services external to odoo.

**Comment by dupski** [comment]
+1 for this. The cron thread is really important. At the moment it can just crash with no logging or automatic restart.

I guess one simple way would be to have a cron task that updates a database value every time the cron runs, then have a healthcheck endpoint that returns when the cron process for a DB last ran, and if it was longer than x minutes, restart the cron process (and raise an alert that there is a problem with the cron scheduler)

**Comment by janikvonrotz** [comment]
@dupski For now I have set up a [Nginx/Loki/Promtail/Grafana](https://janikvonrotz.ch/2021/11/09/nginx-loki-promtail-and-grafana/) to monitor the Odoo instances. It works great.
