### ISSUE TITLE
[all versions] attachment_s3: low performance for /shop

### ISSUE THREAD

**Issue by jjscarafia** [camptocamp/odoo-cloud-platform#318]
This issue is a problem between lower performance accessing s3 objects + some kind of odoo issue.

The problem is that on /shop routes, odoo is calling the method _get_combination_info. And on this method big files are read just to know if they are there (`bool(product.image_1920)`)

For now, we've open https://github.com/odoo/odoo/pull/81767 with a patch to odoo (actually is not a suitable patch)

Anyone else having same issue?

Just changing those lines in odoo we've reduce more that 70% time for /shop route

**Comment by jjscarafia** [comment]
@ayushin maybe this is what you face in https://github.com/camptocamp/odoo-cloud-platform/issues/203

@yvaucher just in case you have any info

@max3903 just in case you face similar issue

**Comment by max3903** [comment]
Ping @JevinD

**Comment by jjscarafia** [comment]
One more thing, same thing [here](https://github.com/odoo/odoo/blob/13.0/addons/website_sale/models/product.py#L341)
1920 image is called on /shop routes just to check if they exist
Maybe there should be a different kind of implementation when checking if the attachment exists rather than when getting the content

**Comment by jjscarafia** [comment]
I believe that using image_128 instead of image_1920 could be the proper solution (check changes on PR)

**Comment by jjscarafia** [comment]
@max3903 @simahawk 
Just to let you know that odoo has merged and improvement for this https://github.com/odoo/odoo/pull/81767#issuecomment-1018396148
Closing

thanks!
