### ISSUE TITLE
Attachments with mimetype application/octet-stream

### ISSUE THREAD

**Issue by jjscarafia** [camptocamp/odoo-cloud-platform#320]
Not sure why but on almost every database we have files with mimetype = 'application/octet-stream'.
By default (by default ir_attachment.storage.force.database value), those files are stored on the object storage.

Some of those files seems to be broken images, some assets (js, css) (for eg /web/js/website.assets_editor/dbe8624, /web/css/website.assets_frontend/ac45671).

I try to verify if those files where actually used, as far as I've tested, at least these are used:
* user_values.scss
* user_color_palette.scss
* user_theme_color_palette.scss
* user_custom_rules.scss

Someone else with same behavior? It would be a good idea to store application/octet-stream on database? Or improve detection of mimetypes? 

Any suggestion?

**Comment by nbessi** [comment]
That issue impacts Odoo Core, there was an issue that affected mime type with azure addons but it was fixed. 
AFAIK cloud addons or not that feature is quite weak in Odoo in general.
