### ISSUE TITLE
base_attachment_object_storage: performance issue with images on tree views

### ISSUE THREAD

**Issue by jjscarafia** [camptocamp/odoo-cloud-platform#372]
Replicated on v13 with attachment_s3 but should be replicable on other versions or other modules that use [base_attachment_object_storage](https://github.com/camptocamp/odoo-cloud-platform/tree/15.0/base_attachment_object_storage)

Steps to reproduce:
--------------------------

1. Use a database with many products with images
2. On product.template tree view add image_128 field (for eg `<field name="image_128" widget="image" string="Imagen"/>`)
3. Go to product.tempalte tree view and with debuger check searc_read time:

    * tree view takes 5x more thatn kanban view (Same image_128 field)
    * using a bigger image (for eg. image_512) make it faster while should be slower because image data is fetched from s3 instead of database

VIDEO: https://drive.google.com/file/d/1hBXIN-gB4bLULsu2y14oRBJUBPVnSgfy/view

**Comment by jjscarafia** [comment]
Hi @simahawk @max3903 

Have you face anything similar? Summarising, using image_128 (image data stored on database) on tree views has a very poor performance.

Thanks!

**Comment by max3903** [comment]
@jjscarafia We haven't faced that issue. Have you tried decreasing the limit in the config parameters to push them to S3?

**Comment by jjscarafia** [comment]
Thanks @max3903 
I will make a deeper analysis.
