### ISSUE TITLE
odoo15 dump the attachments to the minio，can not be  access attachments in odoo.

### ISSUE THREAD

**Issue by caesar168** [camptocamp/odoo-cloud-platform#374]
In the odoo15 version, the attachments originally stored in the database are transferred out to the filtere, and then the env['ir.attachment'] .force_storage() command is executed to dump the attachments to the minio, and then the folder directory is removed (no longer needed). When entering the system, odoo has an error with the following message: Traceback (most recent call last):
  File "/home/vcs/vcs/vcs/addons/base/models/ir_attachment.py", line 119, in _file_read
    with open(full_path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/vcs/vcs/share/filestore/RCB/74/74fb750898f19dc963c14b85fab3b9c734a5b655'。 Since we imported the attachment information into the minio, of course we want to be able to access these attachments in odoo.

**Comment by nbessi** [comment]
@p-tombez @vrenaville might be related to double attachement during migration
