### ISSUE TITLE
base_attachment_object_storage refactored into OCA/storage

### ISSUE THREAD

**Issue by lmignon** [camptocamp/odoo-cloud-platform#418]
The `base_attachment_object_storage` addon is a very good addon that allows to store all the attachments from odoo into an external file system. In an effort to refactor the storage addons from OCA to make them uses the `fsspec` python library as an abstraction layer to any file system where the file content can be stored (see https://github.com/OCA/storage/pull/250-), I have started to think about the possibility to refactor storage_file and storage_image addons to uses the `ir.attachment` model as a storage layer and in the same time define a new kind of field specialized in the storage of file content into an external file system. (Some explanations are provided https://github.com/OCA/storage/pull/252). Time after time, It appear that the way I'll extend the `ir.attachment` model to support the storage through the `fsspec` library will be very similar to the way the `base_attachment_object_storage` addon is implemented with the 'advantage' of being able to support a wide range of file systems without the need to implement a new addon for each file system. To keep your credits for the original implementation, I propose to extract your  `base_attachment_object_storage` with the commit history addon into my PR and then to rename it into `fs_attachment` before starting its refactoring. That also means that the licence will be changed from AGPL to LGTP since my new fields could be used into addon on top of OE addons. (No concrete case at this moment)
Do you agree with this proposal? 

Regards,

ping @jgrandguillaume

**Comment by lmignon** [comment]
You can see the result here https://github.com/OCA/storage/pull/260

**Comment by simahawk** [comment]
@lmignon ciao. Sorry, I'm very late... I had no chance yet to followup w/ this and the PRs for OCA/storage.
I'll have a look in the following weeks. On my side I see no problem w/ the moving and re-licensing for v16.

@grindtildeath as you worked on the subject you could have a look at this.

@vrenaville @gurneyalex something to keep track of for our new image :wink: 

CC @nbessi

**Comment by lmignon** [comment]
@simahawk Thank you for the information. All the functionalities provided by your addons are now covered by the fs_storage and fs_attachment addons. The implementation has been reworked and completed to add new functionalities and improve performances. (you'll find more information into the documentation https://github.com/OCA/storage/pull/260/files#diff-7e7247d9bee562ba2b42edf40dc5eeae9a4c903ca715346527d912829a8077c7R76). I would like to re-license fs_attachment to LGPL now before making the ready for review.
